# Generated by Django 2.1 on 2020-04-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200423_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttopic',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
