# Generated by Django 2.1 on 2020-05-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='topic',
            new_name='topic_id',
        ),
    ]
