# Generated by Django 2.1 on 2020-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200504_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
