# Generated by Django 2.1 on 2020-05-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200504_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostTopic'),
        ),
    ]
