# Generated by Django 2.1 on 2020-05-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200504_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='topic',
            new_name='posts',
        ),
    ]
