# Generated by Django 2.1 on 2020-05-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200504_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
