# Generated by Django 2.1 on 2020-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200504_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='posts',
        ),
        migrations.AddField(
            model_name='like',
            name='posts',
            field=models.ManyToManyField(related_name='likes', to='posts.Post'),
        ),
    ]
