# Generated by Django 2.1 on 2020-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20200504_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
